control:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointVelocityController
    joint: left_wheel_joint
    pid: {p: 0.5, i: 0.0, d: 0.0}
  joint2_position_controller:
    type: effort_controllers/JointVelocityController
    joint: right_wheel_joint
    pid: {p: 0.5, i: 0.0, d: 0.0}
 
# control: 
#   # Publish all joint states -----------------------------------
#   joint_state_controller:
#     type: joint_state_controller/JointStateController
#     publish_rate: 50  
  
#   # Position Controllers ---------------------------------------
#   left_wheel_controller:
#     type: effort_controllers/JointPositionController
#     joint: left_wheel_joint
#     pid: {p: 100.0, i: 0.01, d: 10.0}
#   right_wheel_controller:
#     type: effort_controllers/JointPositionController
#     joint: right_wheel_joint
#     pid: {p: 100.0, i: 0.01, d: 10.0}

